CL_USE_MODULES = Qt4 libtabexchange tracedb-stand libgrx

QT_LIBS = Core

LIBRARY = stand

INCLUDES += -I../..

#EXPORT_INCLUDES = trace.h

MOC_HEADERS = grapher.h paraminfo.h param_select_delegate.h param_select.h params_filter.h

SOURCES = grapher.cpp paraminfo.cpp param_select.cpp param_select_delegate.cpp params_filter.cpp

include $(CL_DIR)/Makefile.cvslvk
